export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_VALUE_ARTICLES = 'FILTER_VALUE_ARTICLES'

export const FILTER_DATE_ARTICLES = 'FILTER_DATE_ARTICLES'

export const FILTERING_ARTICLES_BY_VALUE = 'FILTERING_ARTICLES_BY_VALUE'